---
title: "Notas (es)"
author: "Reinhard Simon"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Diseño Etiquetas}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
# Motivación

Las etiquetas con códigos digitales son una herramienta básica en el seguimiento de materiales genéticos.

# Criterios

Entre los criterios generales de contenido se establece que las etiquetas deben:

1. Identificar un material genético
2. Usar un código fácilmente legible por lectores
3. Visualizar información explicita selecta sobre el material
4. Visualizar información adicional para facilitar el manejo local del grupo

Entre los criterios generales de diseño se establece:

- Los elementos textuales y gráficos deben ser claros para ser leídos rápidamente tanto por maquina como por personas
- Una estructura común y estandarizado también facilita la lectura y comprensión
- Los elementos estructurales deben adaptarse a varios formatos de etiquetas

# Buenas prácticas

- En la medida posible se debe usar estándares populares para bajar costos de adquisición y mantenimiento.
- Se debe usar tecnologías robustas ya que las etiquetas van a ser manipuladas con frecuencia y a veces bajo condiciones duras como en el campo o a temperaturas muy bajas.
- Las etiquetas también deben ser altamente consistentes entre ellos como una medida de calidad y de imagen institucional.
- Se identifica el código 'QR' como la tecnología de impresión de código de barra.
- Los códigos dos dimensionales (2D) son más robustos a desgaste de impresoras ya que con el tiempo las impresoras tienden a saltar líneas lo cual malogra los códigos de barras lineales.
- También los códigos 2D tienen un mejor sistema interno para asegurar la lectura de contenido a pesar de posibles daños locales.
- El código 'QR' es un código actual muy popular y muchos celulares u otros equipos modernos pueden leerlo a parte de los equipos especializados. Esto facilita la implementación y la aceptación.

# Implementación

Correspondiendo a la tarea a) se defino un diseño basado en cuatro bloques cuadráticos. Cada bloque corresponde a uno de los criterios listados. Basado en las modelos de etiquetas disponibles se estableció también que por bloque un máximo de cuatro campos son disponibles.
En más detalle:

1. Bloque ID (identificación): Corresponde a la cabecera de una carta formal: identifica la autoridad, el lugar, la fecha, y el material genético. Secuencia sugerida:
- autoridad: mediante un logotipo
- Unidad (p.e. dirección)
- Subunidad (p.e. colección)
- fecha de impresión
- Código de colección principal
2. Bloque QR: Contiene todos los datos impresos en forma codificada
- Opción para una versión próxima: incluir datos importantes de documentación como en el caso de etiquetar herbarios. Se podrá incluir descripciones del lugar de colecta y otras observaciones.
3. Bloque de información mínima estandarizada. Aquí se podrá incluir cuatro campos. La idea principal es que sean algo común entre colecciones como
- nombre del cultivo
- nombre científico
- fecha indicativo de edad de material (siembra, multiplicación, extracción de ADN, colecta
de herbario, etc)
- proveniencia de material (colección, cruce, país, ...)
4. Bloque información adicional. Idea principal es facilitar informaciones importantes logísticas. Podría incluirse por ejemplo:
- Código de laboratorio o de mejorador
- Método de preparación de material o medio
- Importancia de material: forma parte de una coalición core.
- Estado de limpieza fito sanitario
- Observaciones
- etc.

Se confirmó que los cuatro bloques se pueden organizar en forma de una tabla 2x2 en etiquetas cuadráticas y rectangulares manteniendo legibilidad y un diseño visual atractivo. En etiquetas rectangulares como corbatas de campo se puede organizar los bloques en forma de una fila con cuatro columnas (1x4) o en una columna con cuatro filas (4x1).

Se implemento un algoritmo en 'R' para generar unas muestras para tres diferentes tamaños de etiquetas. El algoritmo acepta principalmente una tabla con los datos entrantes, datos de cabecera, y el nombre de un archivo de plantilla. La tabla entrante debe contar con cuatro hasta ocho campos por material genético. Los tres datos de cabecera son modificable al nivel de lote (es decir se repiten en cada etiqueta) para el bloque ID. Se asume que la autoridad o el 'logotipo' no cambia y este parámetro es solo modificable al nivel de plantilla. La plantilla define varios detalles más específicos como:

- margen alrededor
- Diseño: 2x2, 1x4, 4x1
- Tipo de letra
- Cara de letra: normal, itálica, gruesa, itálica-gruesa
- Tmaño de letra
- Imprimir o no imprimir los nombres de los campos (para mejorar legibilidad en etiquetas chicas y/o ahorrar tinta)
- Espacio entre campos: 1 o 2
- otros en evaluación

Se ha creado cuatro muestras con algunos datos de ejemplo inventados para once materiales en tres colecciones. Cada muestra varia en el diseño un poco dentro de las reglas establecidas.


