---
title: "Notes (en)"
author: "Reinhard Simon"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Label Design}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Motivation

Labels with digital codes are a basic tool in the tracking of genetic materials.

# Criteria

Among the general content criteria it is established that the labels must:

1. identify a genetic material
2. use a code easily readable by readers
3. visualize explicit information about the material
4. display additional information to facilitate the local management of the group

Among the general design criteria is established:

- The textual and graphic elements must be clear to be read quickly by machine or by people
- A common and standardized structure also facilitates reading and comprehension
- Structural elements must adapt to various label formats

# Good practices

- To the extent possible, popular standards should be used to lower acquisition and maintenance costs.
- Robust technologies must be used since the labels are going to be manipulated frequently and sometimes under hard conditions such as in the field or at very low temperatures.
- The labels must also be highly consistent among them as a measure of quality and institutional image.
- The QR code is identified as the 'bar code' printing technology.
- Two dimensional (2D) codes are more robust to printer wear, since over time printers tend to skip lines which spoils the line bar codes.
- Also 2D codes have a better internal system to ensure the reading of content despite possible local damage.
- The QR code is a very popular current code and many cell phones or other modern equipment can read it apart from specialized equipment. This facilitates implementation and acceptance.

# Implementation

Corresponding to task a) a design based on four quadratic blocks was defined. Each block corresponds to one of the listed criteria. Based on the available label models, it was also established that a maximum of four fields are available per block.
In more detail:

1. Block ID (identification): Corresponds to the head of a formal letter: identifies the authority, place, date, and genetic material. Suggested sequence:
- authority: through a logo
- Unit (eg Address)
- Subunit (eg collection)
- printing date
- Main collection code

2. QR Block: Contains all data printed in encrypted form
- Option for a next version: include important documentation data as in the case of labeling herbaria. It may include descriptions of the place of collecta and other observations.

3. Standardized minimum information block. Here you can include four fields. The main idea is that they will be common among collections as
- name of the crop
- scientific name
- Indicative date of material age (sowing, multiplication, extraction of DNA, collecta
herbarium, etc)
- origin of material (collection, crossing, country, ...)

4. Additional information block. Main idea is to provide important logistical information. It could be included for example:
- Laboratory code or improver
- Method of preparation of material or medium
- Material Importance: part of a core collection.
- State of phytosanitary cleaning
- Observations
- etc.

It was confirmed that the four blocks can be organized in the form of a 2x2 table in quadratic and semi-rectangular labels, maintaining a readability and an attractive visual design. In rectangular profiles such as field ties you can organize the blocks in the form of a row with four columns (1x4) or in a column with four rows (4x1).

An algorithm was implemented in R to generate samples for three different sizes of labels. The algorithm mainly accepts a table with the incoming data, header data, and the name of a template file. The incoming table must have four to eight fields per genetic material. The three header data are configurable at the batch level (ie they are repeated on each label) for the ID block. It is assumed that the authority or the logo does not change and this parameter is only configurable at the template level. The template defines several more specific details such as:

- margin around
- layout: 2x2, 1x4, 4x1
- Font
- Fontface: normál, italic, coarse, italico-coarse
- Fontsize
- Print or not print the names of the fields (to improve readability on small labels and / or save ink)
- Space between fields: 1 or 2
- others under evaluation

Four samples have been created with some sample data invented for eleven materials in three collections.
